### ISSUE TITLE
Can the default storage path of the model be set in comfyui models?

### ISSUE THREAD

**Issue by laidingq** [jordoh/ComfyUI-Deepface#1]
Can the default storage path of the model be set in comfyui models?

**Comment by jordoh** [comment]
Sure thing - I've changed the deepface directory to `ComfyUI/models/deepface`, though the deepface only allows so much customization of the location, so it places them in `ComfyUI/models/deepface/.deepface/weights`.

**Comment by laidingq** [comment]
THX
